# Generated by Django 4.0.5 on 2022-07-16 11:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Kategoriya nomi')),
                ('image', models.ImageField(upload_to='category_images')),
                ('products_qty', models.PositiveIntegerField(default=0, verbose_name='Tovarlar soni')),
                ('add_size', models.BooleanField(default=False, verbose_name="Razmer qo'shish")),
                ('add_color', models.BooleanField(default=False, verbose_name="Rang qo'shish")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Rang nomi')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='SubKategoriya nomi')),
                ('products_qty', models.PositiveIntegerField(default=0, verbose_name='Tovarlar soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'SubKategoriya',
                'verbose_name_plural': 'SubKategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Kategoriya nomi')),
                ('image', models.ImageField(upload_to='category_images')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('description', models.TextField(verbose_name='Tovar haqida')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Reyting')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('size', models.CharField(blank=True, choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=5, verbose_name='Razmeri')),
                ('prise_uzs', models.PositiveIntegerField(default=0, verbose_name='Narxi uzs')),
                ('prise_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Narxi usd')),
                ('prise_rub', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Narxi rub')),
                ('options', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Kategoriyasi')),
                ('colors', models.ManyToManyField(to='main.colors')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subcategory', verbose_name='Kategoriyasi')),
            ],
        ),
    ]
