# Generated by Django 4.0.5 on 2022-07-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Banner nomi')),
                ('description', models.TextField(verbose_name='Banner teksti')),
                ('image', models.ImageField(upload_to='banner_images', verbose_name='Banner rasmi')),
                ('banner_type', models.CharField(choices=[('Big', 'big'), ('Medium', 'medium'), ('Small', 'small')], max_length=25, verbose_name='Banner turi')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images', verbose_name='Tovar rasmi '),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Tovar nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subcategory', verbose_name='SubKategoriyasi'),
        ),
    ]
