# Generated by Django 4.0.5 on 2022-07-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner_alter_product_image_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
    ]
