# Generated by Django 4.0.5 on 2022-07-19 12:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Banner teksti'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Banner teksti'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Banner teksti'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Banner nomi'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Banner nomi'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Banner nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tovar haqida'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tovar haqida'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tovar haqida'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Tovar nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Tovar nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Tovar nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='options_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='options_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='options_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='SubKategoriya nomi'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='SubKategoriya nomi'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='SubKategoriya nomi'),
        ),
    ]
