# Generated by Django 4.0.5 on 2022-07-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_banner_description_en_banner_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorys', to='main.category', verbose_name='Kategoriyasi'),
        ),
    ]
